---
abstract: 'Testing report storage Server'
author:
  - 'tokuhirom <tokuhirom@gmail.com>'
build_requires:
  HTTP::Message::PSGI: '0'
  LWP::Protocol::PSGI: '0'
  Plack::Test: '0'
  Plack::Util: '0'
  Test::More: '0.98'
  Test::Requires: '0'
  Test::WWW::Mechanize::PSGI: '0'
  autodie: '0'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Ukigumo-Server
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Ukigumo::Server:
    file: lib/Ukigumo/Server.pm
    version: v2.0.2
  Ukigumo::Server::API:
    file: lib/Ukigumo/Server/API.pm
  Ukigumo::Server::API::Dispatcher:
    file: lib/Ukigumo/Server/API/Dispatcher.pm
  Ukigumo::Server::Command::Branch:
    file: lib/Ukigumo/Server/Command/Branch.pm
  Ukigumo::Server::Command::Docs:
    file: lib/Ukigumo/Server/Command/Docs.pm
  Ukigumo::Server::Command::Report:
    file: lib/Ukigumo/Server/Command/Report.pm
  Ukigumo::Server::DB:
    file: lib/Ukigumo/Server/DB.pm
  Ukigumo::Server::DB::Schema:
    file: lib/Ukigumo/Server/DB/Schema.pm
  Ukigumo::Server::L10N:
    file: lib/Ukigumo/Server/L10N.pm
  Ukigumo::Server::Launcher:
    file: lib/Ukigumo/Server/Launcher.pm
  Ukigumo::Server::Schema:
    file: lib/Ukigumo/Server/Schema.pm
  Ukigumo::Server::Util:
    file: lib/Ukigumo/Server/Util.pm
  Ukigumo::Server::Web:
    file: lib/Ukigumo/Server/Web.pm
  Ukigumo::Server::Web::Dispatcher:
    file: lib/Ukigumo/Server/Web/Dispatcher.pm
  Ukigumo::Server::Web::ViewFunctions:
    file: lib/Ukigumo/Server/Web/ViewFunctions.pm
requires:
  Amon2: '2.50'
  Amon2::Declare: '0'
  Amon2::Plugin::ShareDir: '0'
  Amon2::Web: '0'
  Amon2::Web::Dispatcher::Lite: '0'
  Capture::Tiny: '0'
  Compress::Zlib: '0'
  DBD::SQLite: '1.33'
  DBI: '0'
  Data::Page::NoTotalEntries: '0.02'
  Data::Validator: '0.08'
  File::Find::Rule: '0'
  File::ShareDir: '0'
  FindBin::libs: '0'
  Getopt::Long: '0'
  HTML::FromANSI::Tiny: '0'
  JSON: '2'
  LWP::UserAgent: '0'
  Locale::Maketext::Extract: '0'
  Locale::Maketext::Lexicon: '0'
  Module::Functions: '0'
  Plack::Builder: '0'
  Plack::Loader: '0'
  Plack::Middleware::ReverseProxy: '0.09'
  Plack::Middleware::Session: '0.14'
  Plack::Session::Store::File: '0'
  Pod::Usage: '0'
  Router::Simple: '0.14'
  Router::Simple::Sinatraish: '0'
  Starlet: '0'
  Teng: '0'
  Text::Markdown: '1'
  Text::Xslate: '1.1005'
  Text::Xslate::Util: '0'
  Time::Duration: '0'
  Time::Duration::ja: '0.03'
  Time::Piece: '1.20'
  URI::Escape: '0'
  URI::WithBase: '0'
  Ukigumo::Common: '0.04'
  Ukigumo::Constants: '0'
  parent: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/ukigumo/ukigumo-server/issues
  homepage: https://github.com/ukigumo/ukigumo-server
  repository: git://github.com/ukigumo/ukigumo-server.git
version: v2.0.2
x_contributors:
  - 'xaicron <xaicron@gmail.com>'
  - 'Kan Fushihara <kan@fout.jp>'
  - 'mattn <mattn.jp@gmail.com>'
  - 'Kan Fushihara <kan.fushihara@gmail.com>'
  - 'Tomohiro Hosaka <bokutin@bokut.in>'
  - 'studio3104 <studio3104.com@gmail.com>'
  - 'HIROSE Masaaki <hirose31@gmail.com>'
  - 'Takumi Sakamoto <takumi.saka@gmail.com>'
  - 'Songmu <y.songmu@gmail.com>'
  - 'cho45 <cho45@lowreal.net>'
  - 'moznion <moznion@gmail.com>'
